import traceback
from contextlib import asynccontextmanager
from typing import Annotated, Any, TypedDict
from fastapi import FastAPI, Request
from fastapi.responses import StreamingResponse
from langchain_core.messages import BaseMessage, HumanMessage, RemoveMessage
from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder
from langchain_core.runnables import RunnableConfig
from langchain_ollama import ChatOllama
from langgraph.checkpoint.redis import RedisSaver
from langgraph.graph import END, START, StateGraph
from langgraph.graph.message import add_messages
from pydantic import BaseModel


# 1. Manage Redis connection lifecycle using Lifespan (fix context manager issue)
@asynccontextmanager
async def lifespan(app: FastAPI):
    REDIS_URL = "redis://localhost:6380"
    print("[SYSTEM] Connecting and initializing Redis Checkpointer...")

    try:
        # 1. Initialize Context Manager (this is a sync context manager)
        redis_context = RedisSaver.from_conn_string(REDIS_URL)

        # 2. Use a plain 'with' block to extract the actual 'saver' instance
        with redis_context as saver:
            print(
                "[SYSTEM] Successfully initialized indices and Redis Checkpointer configuration!"
            )

            # Store the actual checkpointer object (correct type) into app state
            app.state.checkpointer = saver
            # 3. Compile the graph once here
            workflow = StateGraph(State)
            workflow.add_node("agent", call_model)
            workflow.add_node("summarize_node", summarize_conversation)
            workflow.add_edge(START, "agent")
            workflow.add_conditional_edges("agent", should_summarize)
            workflow.add_edge("summarize_node", END)

            # At this point, saver is a valid BaseCheckpointSaver, so no type warnings
            app.state.graph_app = workflow.compile(checkpointer=saver)

            # 4. Keep FastAPI running to serve requests
            # Redis connection will be kept alive because we are still inside the 'with' block
            yield

        # When you stop the server (Ctrl + C), FastAPI exits the yield,
        # and the 'with' block will automatically close Redis safely here.
        print("[SYSTEM] Closing Redis Checkpointer safely...")

    except Exception as env_err:
        print(f"[SYSTEM CRITICAL ERROR INITIALIZING REDIS]: {traceback.format_exc()}")
        raise env_err


app = FastAPI(title="Modern LangGraph Chat with Lifespan", lifespan=lifespan)

# 2. Initialize LLM model
llm = ChatOllama(model="llama3:8b")


# 3. Define State structure
class State(TypedDict):
    messages: Annotated[list[BaseMessage], add_messages]
    summary: str  # store long-term memory summary


# 4. Define LLM processing node
prompt_template = ChatPromptTemplate.from_messages(
    [
        ("system", "{system_context}"),  # Injected dynamically here
        MessagesPlaceholder(variable_name="messages"),
    ]
)


def call_model(state: State):
    chain = prompt_template | llm
    existing_summary = state.get("summary", "")

    system_context = (
        "You are an intelligent AI assistant. Respond naturally in English."
    )
    if existing_summary:
        system_context += (
            f" Summary of previous conversation context: {existing_summary}"
        )

    # Passing system_context as a placeholder value directly into the template
    response = chain.invoke(
        {"system_context": system_context, "messages": state["messages"]}
    )
    return {"messages": [response]}


# 5. Client request structure
class ChatRequest(BaseModel):
    prompt: str
    session_id: str


# 6. Synchronous generator for LangGraph token streaming
def stream_langgraph_response(prompt: str, session_id: str, graph_app: Any):
    try:
        config: RunnableConfig = {"configurable": {"thread_id": session_id}}
        input_data: Any = {"messages": [HumanMessage(content=prompt)]}

        print(f"[BACKEND LOG] Running graph stream for Thread: {session_id}...")

        # Use stream_mode "messages" to receive EACH token generated by the LLM
        for msg, metadata in graph_app.stream(
            input=input_data, config=config, stream_mode="messages"
        ):
            # Only process tokens from the 'agent' node (avoid echoing user input)
            if metadata.get("langgraph_node") == "agent":
                if hasattr(msg, "content") and msg.content:
                    # Yield SSE-formatted response
                    yield f"data: {msg.content}\n\n"

    except Exception as e:
        print("\n" + "=" * 50)
        print("[CRITICAL ERROR IN STREAM]:")
        print(traceback.format_exc())
        print("=" * 50 + "\n")
        yield "data: Error details: Check Backend Terminal\n\n"


def summarize_conversation(state: State):
    """Compresses oldest messages into text and issues deletion commands to Redis."""
    messages = state["messages"]
    existing_summary = state.get("summary", "")

    if len(messages) < 6:
        return {}

    print(f"\n[MEMORY SYSTEM] Detected {len(messages)} messages. Compressing memory...")
    messages_to_summarize = messages[:-2]

    summary_prompt = (
        f"Progressively summarize the lines of conversation provided below concisely. "
        f"If a previous summary exists ({existing_summary}), incorporate the new context into it. "
        f"Return ONLY the plain summary text.\n\n"
    )
    for m in messages_to_summarize:
        role = "User" if isinstance(m, HumanMessage) else "AI"
        summary_prompt += f"{role}: {m.content}\n"

    new_summary = llm.invoke(summary_prompt)
    print(f"[MEMORY SYSTEM] Updated Summary: {new_summary}")

    # Generate directives to drop strings from Redis memory window
    delete_messages = [
        RemoveMessage(id=str(m.id)) for m in messages_to_summarize if m.id is not None
    ]

    return {"summary": str(new_summary), "messages": delete_messages}


def should_summarize(state: State):
    """Decides whether to go the summary node."""
    if len(state["messages"]) >= 6:
        return "summarize_node"
    return END


@app.post("/api/chat")
async def chat_endpoint(request: ChatRequest, fastapi_req: Request):
    print(f"\n[BACKEND LOG] Received request from Session: {request.session_id}")

    # Get precompiled graph from app state
    graph_app = fastapi_req.app.state.graph_app

    # Return streaming response (Event-Stream)
    return StreamingResponse(
        stream_langgraph_response(request.prompt, request.session_id, graph_app),
        media_type="text/event-stream",
    )


if __name__ == "__main__":
    import uvicorn

    # Run the application using uvicorn
    uvicorn.run(app, host="127.0.0.1", port=8000)
