import traceback
from contextlib import asynccontextmanager
from typing import Annotated, Any, TypedDict
from fastapi import FastAPI, Request
from fastapi.responses import StreamingResponse
from langchain_core.messages import BaseMessage, HumanMessage
from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder
from langchain_core.runnables import RunnableConfig
from langchain_ollama import ChatOllama
from langgraph.checkpoint.redis import RedisSaver
from langgraph.graph import END, START, StateGraph
from langgraph.graph.message import add_messages
from pydantic import BaseModel


# 1. Manage Redis connection lifecycle using Lifespan (fix context manager issue)
@asynccontextmanager
async def lifespan(app: FastAPI):
    REDIS_URL = "redis://localhost:6380"
    print("[SYSTEM] Connecting and initializing Redis Checkpointer...")

    try:
        # 1. Initialize Context Manager (this is a sync context manager)
        redis_context = RedisSaver.from_conn_string(REDIS_URL)

        # 2. Use a plain 'with' block to extract the actual 'saver' instance
        with redis_context as saver:
            print(
                "[SYSTEM] Successfully initialized indices and Redis Checkpointer configuration!"
            )

            # Store the actual checkpointer object (correct type) into app state
            app.state.checkpointer = saver

            # 3. Compile the graph once here
            workflow = StateGraph(State)
            workflow.add_node("agent", call_model)
            workflow.add_edge(START, "agent")
            workflow.add_edge("agent", END)

            # At this point, saver is a valid BaseCheckpointSaver, so no type warnings
            app.state.graph_app = workflow.compile(checkpointer=saver)

            # 4. Keep FastAPI running to serve requests
            # Redis connection will be kept alive because we are still inside the 'with' block
            yield

        # When you stop the server (Ctrl + C), FastAPI exits the yield,
        # and the 'with' block will automatically close Redis safely here.
        print("[SYSTEM] Closing Redis Checkpointer safely...")

    except Exception as env_err:
        print(f"[SYSTEM CRITICAL ERROR INITIALIZING REDIS]: {traceback.format_exc()}")
        raise env_err


app = FastAPI(title="Modern LangGraph Chat with Lifespan", lifespan=lifespan)

# 2. Initialize LLM model
llm = ChatOllama(model="llama3:8b")


# 3. Define State structure
class State(TypedDict):
    messages: Annotated[list[BaseMessage], add_messages]
    summary: str  # store long-term memory summary


# 4. Define LLM processing node
prompt_template = ChatPromptTemplate.from_messages(
    [
        (
            "system",
            "You are an intelligent AI assistant. Use the conversation history to respond logically.",
        ),
        MessagesPlaceholder(variable_name="messages"),
    ]
)


def call_model(state: State):
    print("[NODE] Executing Agent Node...")
    chain = prompt_template | llm
    response = chain.invoke({"messages": state["messages"]})
    return {"messages": [response]}


# 5. Client request structure
class ChatRequest(BaseModel):
    prompt: str
    session_id: str


# 6. Synchronous generator for LangGraph token streaming
def stream_langgraph_response(prompt: str, session_id: str, graph_app: Any):
    try:
        config: RunnableConfig = {"configurable": {"thread_id": session_id}}
        input_data: Any = {"messages": [HumanMessage(content=prompt)]}

        print(f"[BACKEND LOG] Running graph stream for Thread: {session_id}...")

        # Use stream_mode "messages" to receive EACH token generated by the LLM
        for msg, metadata in graph_app.stream(
            input=input_data, config=config, stream_mode="messages"
        ):
            # Only process tokens from the 'agent' node (avoid echoing user input)
            if metadata.get("langgraph_node") == "agent":
                if hasattr(msg, "content") and msg.content:
                    # Print to terminal for debugging
                    print(msg.content, end="", flush=True)
                    # Yield SSE-formatted response
                    yield f"data: {msg.content}\n\n"

    except Exception as e:
        print("\n" + "=" * 50)
        print("[CRITICAL ERROR IN STREAM]:")
        print(traceback.format_exc())
        print("=" * 50 + "\n")
        yield "data: Error details: Check Backend Terminal\n\n"


@app.post("/api/chat")
async def chat_endpoint(request: ChatRequest, fastapi_req: Request):
    print(f"\n[BACKEND LOG] Received request from Session: {request.session_id}")

    # Get precompiled graph from app state
    graph_app = fastapi_req.app.state.graph_app

    # Return streaming response (Event-Stream)
    return StreamingResponse(
        stream_langgraph_response(request.prompt, request.session_id, graph_app),
        media_type="text/event-stream",
    )


if __name__ == "__main__":
    import uvicorn

    # Run the application using uvicorn
    uvicorn.run(app, host="127.0.0.1", port=8000)
